//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastebookEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASTEBOOK_LIKE
    {
        public int ID { get; set; }
        public int POST_ID { get; set; }
        public int LIKED_BY { get; set; }
    
        public virtual PASTEBOOK_USER PASTEBOOK_USER { get; set; }
        public virtual PASTEBOOK_POST PASTEBOOK_POST { get; set; }
    }
}
