//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastebookEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASTEBOOK_FRIEND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PASTEBOOK_FRIEND()
        {
            this.PASTEBOOK_NOTIFICATION = new HashSet<PASTEBOOK_NOTIFICATION>();
        }
    
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int FRIEND_ID { get; set; }
        public string REQUEST { get; set; }
        public string IsBLOCKED { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    
        public virtual PASTEBOOK_USER PASTEBOOK_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASTEBOOK_NOTIFICATION> PASTEBOOK_NOTIFICATION { get; set; }
        public virtual PASTEBOOK_USER PASTEBOOK_USER1 { get; set; }
    }
}
