//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastebookEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.FRIENDs = new HashSet<FRIEND>();
            this.FRIENDs1 = new HashSet<FRIEND>();
            this.LIKEs = new HashSet<LIKE>();
            this.NOTIFICATIONs = new HashSet<NOTIFICATION>();
            this.NOTIFICATIONs1 = new HashSet<NOTIFICATION>();
            this.POSTs = new HashSet<POST>();
            this.POSTs1 = new HashSet<POST>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Username is required")]
        [StringLength(50, ErrorMessage = "Maximum characters for username is 50")]
        [RegularExpression("^[a-zA-Z0-9]+([._]?[a-zA-Z0-9]+)*$", ErrorMessage = "Invalid username. Username can only start with alphabet character and number. It cannot contains trailing period(.) or underscore(_). Username can end with alphabet character or number.")]
        [DisplayName("Username")]
        public string USER_NAME { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [StringLength(50, ErrorMessage = "Maximum characters for password is 50")]
        public string PASSWORD { get; set; }

        public string SALT { get; set; }

        [Required(ErrorMessage = "First name is required")]
        [DisplayName("First Name")]
        [StringLength(50, ErrorMessage = "Maximum characters for first name is 50")]
        [RegularExpression("^[a-zA-Z0-9]+([. ]?[a-zA-Z0-9]+[.]?)*$", ErrorMessage = "Invalid first name. First name cannot contain special characters, except period(.), hyphen(-) but it cannot contains trailing period and hyphen. It can end with alphabet character, number or period.")]
        public string FIRST_NAME { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        [DisplayName("Last Name")]
        [StringLength(50, ErrorMessage = "Maximum characters for last name is 50")]
        [RegularExpression("^[a-zA-Z0-9]+([. ]?[a-zA-Z0-9]+[.]?)*$", ErrorMessage = "Invalid last name. First name cannot contain special characters, except period(.), hyphen(-) but it cannot contains trailing period and hyphen. It can end with alphabet character, number or period.")]
        public string LAST_NAME { get; set; }

        [Required(ErrorMessage = "Birthday is required")]
        [DisplayName("Birthday")]
        public System.DateTime BIRTHDAY { get; set; }

        [DisplayName("Country")]
        public Nullable<int> COUNTRY_ID { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Phone]
        public string MOBILE_NO { get; set; }

        [DisplayName("Gender")]
        public string GENDER { get; set; }
        public byte[] PROFILE_PIC { get; set; }

        [DisplayName("Joined Pastebook")]
        public System.DateTime DATE_CREATED { get; set; }

        [DisplayName("About Me")]
        public string ABOUT_ME { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [DisplayName("Email Address")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRIEND> FRIENDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRIEND> FRIENDs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIKE> LIKEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POSTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POSTs1 { get; set; }
        public virtual REF_COUNTRY REF_COUNTRY { get; set; }
    }
}
